from __future__ import annotations

from enum import StrEnum


class DecisionState(StrEnum):
    ANSWER = "ANSWER"
    ASK = "ASK"
    ABSTAIN = "ABSTAIN"
    PRE_ANSWER = "PRE_ANSWER"


class ReasonCode(StrEnum):
    # ASK
    MISSING_RETURN_PERIOD = "MISSING_RETURN_PERIOD"
    AMBIGUOUS_PRODUCT_SCOPE = "AMBIGUOUS_PRODUCT_SCOPE"
    VAGUE_PREFERENCE = "VAGUE_PREFERENCE"
    AMBIGUOUS_ENTITY = "AMBIGUOUS_ENTITY"
    MISSING_COMPARISON_PRIORITY = "MISSING_COMPARISON_PRIORITY"
    MISSING_FILTERS = "MISSING_FILTERS"
    MISSING_RANKING = "MISSING_RANKING"
    MISSING_LOOKUP_TARGET = "MISSING_LOOKUP_TARGET"

    # ABSTAIN
    UNSUPPORTED_PREDICTION = "UNSUPPORTED_PREDICTION"
    FIELD_NOT_AVAILABLE = "FIELD_NOT_AVAILABLE"
    UNKNOWN_CODE_MEANING = "UNKNOWN_CODE_MEANING"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    NO_VALID_CANDIDATE = "NO_VALID_CANDIDATE"
    QUALITY_BLOCKED = "QUALITY_BLOCKED"
    EXTERNAL_EVIDENCE_MISSING = "EXTERNAL_EVIDENCE_MISSING"
    INCOMPARABLE_METRICS = "INCOMPARABLE_METRICS"
    VALIDATION_FAILED = "VALIDATION_FAILED"

    # ANSWER / trace
    EVIDENCE_READY = "EVIDENCE_READY"
    PARTIAL_CANDIDATE_REMOVED = "PARTIAL_CANDIDATE_REMOVED"


VALIDATION_TO_REASON: dict[str, ReasonCode] = {
    "MISSING_FILTERS": ReasonCode.MISSING_FILTERS,
    "MISSING_RANKING": ReasonCode.MISSING_RANKING,
    "MISSING_LOOKUP_TARGET": ReasonCode.MISSING_LOOKUP_TARGET,
    "MISSING_RELATIONSHIP_FILTERS": ReasonCode.MISSING_FILTERS,
    "FIELD_NOT_SUPPORTED_FOR_FAMILY": ReasonCode.AMBIGUOUS_PRODUCT_SCOPE,
    "UNKNOWN_FIELD": ReasonCode.FIELD_NOT_AVAILABLE,
    "RANK_BLOCKED_FIELD": ReasonCode.FIELD_NOT_AVAILABLE,
    "UNSUPPORTED_PREDICTION_NOT_EXECUTABLE": ReasonCode.UNSUPPORTED_PREDICTION,
}
